###

GET http://localhost:3000/products
Authorization: Bearer {{ jwt }}

### Get all products

# @name createProduct
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Refrigerante Coca-Cola 1L",
  "slug": "refrigerante-coca-cola-1l",
  "description": "Refrigerante Coca-Cola 1L",
  "price": 799,
  "image": "https://images.tcdn.com.br/img/img_prod/1115696/coca_cola_pet_1l_13_1_b28aa1d4aa4d9eb3d6d7d9c8eb5e9cdf.jpg",
  "isActive": true
}

###

# @name createFalvor
POST http://localhost:3000/flavors
Content-Type: application/json

{
  "name": "Romeu e Julieta",
  "slug": "romeu-e-julieta",
  "type": "DOCE",
  "description": "Queijo mussarela e goiabada.",
  "prices": { "middle": 4000, "large": 5000, "family": 5600 }
}



### Create a new product

@productId = {{ createProduct.response.body.id }}

GET http://localhost:3000/products/{{productId}}


### Get product by ID

PATCH http://localhost:3000/products/{{productId}}

### Update product by ID

DELETE http://localhost:3000/products/{{productId}}


### Register a new user
POST http://localhost:3000/auth/register
Content-Type: application/json  

{
   "name": "Davi Lima",
  "phone": "(71) 98452-7435",
  "address": {
    "street": "Rua Exemplo",
    "number": "123",
    "city": "Salvador",
    "state": "BA",
    "zipCode": "40000-000"
  },
  "email": "novodavilima1@gmail.com",
  "password": "senha123"
}

### Login user
# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "novodavilima1@gmail.com",
  "password": "senha123"
}

###

@jwt = {{ login.response.body.access_token }}

###
GET http://localhost:3000/flavors